FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

RUN addgroup -S resit && adduser -S resit -G resit
COPY --from=builder --chown=resit:resit /app/.next/standalone ./
COPY --from=builder --chown=resit:resit /app/.next/static ./.next/static
COPY --from=builder --chown=resit:resit /app/public ./public

USER resit
EXPOSE 3000
CMD ["node", "server.js"]
